version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - STREAMLIT_SERVER_ADDRESS=192.168.0.111
      - STREAMLIT_SERVER_PORT=8501
